<?php

namespace Database\Seeders;

use App\Models\Achievement;
use Illuminate\Database\Seeder;

class AchievementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Achievement::whereIn('code', [
            'streak.learning_begins',
            'streak.consistent_learner',
        ])->update(['is_active' => false]);

        $achievements = [
            [
                'code' => 'onboarding.welcome_aboard',
                'name' => 'Welcome Aboard',
                'description' => 'Created an account on Tutorial Center Africa.',
                'category' => 'onboarding',
                'type' => 'badge',
                'scope' => 'once',
                'progressive' => true,
                'display_order' => 1,
                'requirements' => [
                    'event' => 'student_registered',
                ],
            ],
            [
                'code' => 'onboarding.profile_complete',
                'name' => 'Profile Complete',
                'description' => 'Completed all required profile information.',
                'category' => 'onboarding',
                'type' => 'badge',
                'scope' => 'once',
                'progressive' => true,
                'display_order' => 2,
                'requirements' => [
                    'event' => 'profile_completed',
                ],
            ],
            [
                'code' => 'onboarding.ready_to_learn',
                'name' => 'Ready to Learn',
                'description' => 'Selected an exam type and subjects.',
                'category' => 'onboarding',
                'type' => 'badge',
                'scope' => 'once',
                'progressive' => true,
                'display_order' => 3,
                'requirements' => [
                    'event' => 'exam_type_and_subjects_selected',
                ],
            ],
            [
                'code' => 'onboarding.first_step',
                'name' => 'First Step',
                'description' => 'Started the first exam-practice attempt.',
                'category' => 'onboarding',
                'type' => 'badge',
                'scope' => 'once',
                'progressive' => true,
                'display_order' => 4,
                'requirements' => [
                    'event' => 'exam_attempt_started',
                ],
            ],
            [
                'code' => 'onboarding.first_answer',
                'name' => 'First Answer',
                'description' => 'Submitted the first answer in exam practice.',
                'category' => 'onboarding',
                'type' => 'badge',
                'scope' => 'once',
                'progressive' => true,
                'display_order' => 5,
                'requirements' => [
                    'event' => 'exam_answer_submitted',
                ],
            ],
            [
                'code' => 'onboarding.practice_starter',
                'name' => 'Practice Starter',
                'description' => 'Completed the first exam-practice attempt.',
                'category' => 'onboarding',
                'type' => 'badge',
                'scope' => 'once',
                'progressive' => true,
                'display_order' => 6,
                'requirements' => [
                    'event' => 'exam_attempt_completed',
                ],
            ],
            [
                'code' => 'onboarding.first_achievement',
                'name' => 'First Achievement',
                'description' => 'Earned the first qualifying non-onboarding achievement.',
                'category' => 'onboarding',
                'type' => 'badge',
                'scope' => 'once',
                'progressive' => true,
                'display_order' => 7,
                'requirements' => [
                    'event' => 'qualifying_non_onboarding_achievement_awarded',
                    'excluded_category' => 'onboarding',
                ],
            ],
            [
                'code' => 'practice.question_explorer',
                'name' => 'Question Explorer',
                'description' => 'Answered 50 eligible exam-practice questions.',
                'category' => 'practice_milestone',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 1,
                'requirements' => ['eligible_answers' => 50],
            ],
            [
                'code' => 'practice.question_challenger',
                'name' => 'Question Challenger',
                'description' => 'Answered 100 eligible exam-practice questions.',
                'category' => 'practice_milestone',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 2,
                'requirements' => ['eligible_answers' => 100],
            ],
            [
                'code' => 'practice.knowledge_hunter',
                'name' => 'Knowledge Hunter',
                'description' => 'Answered 250 eligible exam-practice questions.',
                'category' => 'practice_milestone',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 3,
                'requirements' => ['eligible_answers' => 250],
            ],
            [
                'code' => 'practice.study_warrior',
                'name' => 'Study Warrior',
                'description' => 'Answered 500 eligible exam-practice questions.',
                'category' => 'practice_milestone',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 4,
                'requirements' => ['eligible_answers' => 500],
            ],
            [
                'code' => 'practice.academic_hero',
                'name' => 'Academic Hero',
                'description' => 'Answered 1,000 eligible exam-practice questions.',
                'category' => 'practice_milestone',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 5,
                'requirements' => ['eligible_answers' => 1000],
            ],
            [
                'code' => 'practice.practice_champion',
                'name' => 'Practice Champion',
                'description' => 'Answered 2,500 eligible exam-practice questions.',
                'category' => 'practice_milestone',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 6,
                'requirements' => ['eligible_answers' => 2500],
            ],
            [
                'code' => 'practice.learning_machine',
                'name' => 'Learning Machine',
                'description' => 'Answered 5,000 eligible exam-practice questions.',
                'category' => 'practice_milestone',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 7,
                'requirements' => ['eligible_answers' => 5000],
            ],
            [
                'code' => 'practice.master_scholar',
                'name' => 'Master Scholar',
                'description' => 'Answered 10,000 eligible exam-practice questions.',
                'category' => 'practice_milestone',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 8,
                'requirements' => ['eligible_answers' => 10000],
            ],
            [
                'code' => 'practice.education_legend',
                'name' => 'Education Legend',
                'description' => 'Answered 25,000 eligible exam-practice questions.',
                'category' => 'practice_milestone',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 9,
                'requirements' => ['eligible_answers' => 25000],
            ],
            [
                'code' => 'weekly_accuracy.bronze',
                'name' => 'Bronze Accuracy',
                'description' => 'Achieved at least 60% weekly exam-practice accuracy.',
                'category' => 'weekly_accuracy',
                'type' => 'medal',
                'tier' => 'bronze',
                'scope' => 'weekly',
                'repeatable' => true,
                'progressive' => false,
                'display_order' => 1,
                'requirements' => [
                    'minimum_completed_attempts' => 6,
                    'minimum_accuracy_percentage' => 60,
                    'maximum_accuracy_percentage' => 69.9999,
                    'accuracy_scope' => 'all_subjects',
                    'accuracy_denominator' => 'all_questions',
                ],
            ],
            [
                'code' => 'weekly_accuracy.silver',
                'name' => 'Silver Accuracy',
                'description' => 'Achieved at least 70% weekly exam-practice accuracy.',
                'category' => 'weekly_accuracy',
                'type' => 'medal',
                'tier' => 'silver',
                'scope' => 'weekly',
                'repeatable' => true,
                'progressive' => false,
                'display_order' => 2,
                'requirements' => [
                    'minimum_completed_attempts' => 6,
                    'minimum_accuracy_percentage' => 70,
                    'maximum_accuracy_percentage' => 79.9999,
                    'accuracy_scope' => 'all_subjects',
                    'accuracy_denominator' => 'all_questions',
                ],
            ],
            [
                'code' => 'weekly_accuracy.gold',
                'name' => 'Gold Accuracy',
                'description' => 'Achieved at least 80% weekly exam-practice accuracy.',
                'category' => 'weekly_accuracy',
                'type' => 'medal',
                'tier' => 'gold',
                'scope' => 'weekly',
                'repeatable' => true,
                'progressive' => false,
                'display_order' => 3,
                'requirements' => [
                    'minimum_completed_attempts' => 6,
                    'minimum_accuracy_percentage' => 80,
                    'maximum_accuracy_percentage' => 89.9999,
                    'accuracy_scope' => 'all_subjects',
                    'accuracy_denominator' => 'all_questions',
                ],
            ],
            [
                'code' => 'weekly_accuracy.platinum',
                'name' => 'Platinum Accuracy',
                'description' => 'Achieved at least 90% weekly exam-practice accuracy.',
                'category' => 'weekly_accuracy',
                'type' => 'medal',
                'tier' => 'platinum',
                'scope' => 'weekly',
                'repeatable' => true,
                'progressive' => false,
                'display_order' => 4,
                'requirements' => [
                    'minimum_completed_attempts' => 6,
                    'minimum_accuracy_percentage' => 90,
                    'maximum_accuracy_percentage' => 94.9999,
                    'accuracy_scope' => 'all_subjects',
                    'accuracy_denominator' => 'all_questions',
                ],
            ],
            [
                'code' => 'weekly_accuracy.diamond',
                'name' => 'Diamond Accuracy',
                'description' => 'Achieved at least 95% weekly exam-practice accuracy.',
                'category' => 'weekly_accuracy',
                'type' => 'medal',
                'tier' => 'diamond',
                'scope' => 'weekly',
                'repeatable' => true,
                'progressive' => false,
                'display_order' => 5,
                'requirements' => [
                    'minimum_completed_attempts' => 6,
                    'minimum_accuracy_percentage' => 95,
                    'maximum_accuracy_percentage' => 99.9999,
                    'accuracy_scope' => 'all_subjects',
                    'accuracy_denominator' => 'all_questions',
                ],
            ],
            [
                'code' => 'weekly_accuracy.perfect_genius',
                'name' => 'Perfect Genius',
                'description' => 'Achieved 100% weekly exam-practice accuracy.',
                'category' => 'weekly_accuracy',
                'type' => 'medal',
                'tier' => 'perfect',
                'scope' => 'weekly',
                'repeatable' => true,
                'progressive' => false,
                'display_order' => 6,
                'requirements' => [
                    'minimum_completed_attempts' => 6,
                    'minimum_accuracy_percentage' => 100,
                    'maximum_accuracy_percentage' => 100,
                    'accuracy_scope' => 'all_subjects',
                    'accuracy_denominator' => 'all_questions',
                ],
            ],
            [
                'code' => 'exam_performance.bronze',
                'name' => 'Bronze Subject Performance',
                'description' => 'Scored at least 60% in a completed subject exam practice.',
                'category' => 'exam_performance',
                'type' => 'medal',
                'tier' => 'bronze',
                'scope' => 'attempt',
                'repeatable' => true,
                'progressive' => false,
                'display_order' => 1,
                'requirements' => [
                    'attempt_status' => 'completed',
                    'minimum_accuracy_percentage' => 60,
                    'maximum_accuracy_percentage' => 69.9999,
                    'accuracy_denominator' => 'all_questions',
                    'subject_scoped' => true,
                ],
            ],
            [
                'code' => 'exam_performance.silver',
                'name' => 'Silver Subject Performance',
                'description' => 'Scored at least 70% in a completed subject exam practice.',
                'category' => 'exam_performance',
                'type' => 'medal',
                'tier' => 'silver',
                'scope' => 'attempt',
                'repeatable' => true,
                'progressive' => false,
                'display_order' => 2,
                'requirements' => [
                    'attempt_status' => 'completed',
                    'minimum_accuracy_percentage' => 70,
                    'maximum_accuracy_percentage' => 79.9999,
                    'accuracy_denominator' => 'all_questions',
                    'subject_scoped' => true,
                ],
            ],
            [
                'code' => 'exam_performance.gold',
                'name' => 'Gold Subject Performance',
                'description' => 'Scored at least 80% in a completed subject exam practice.',
                'category' => 'exam_performance',
                'type' => 'medal',
                'tier' => 'gold',
                'scope' => 'attempt',
                'repeatable' => true,
                'progressive' => false,
                'display_order' => 3,
                'requirements' => [
                    'attempt_status' => 'completed',
                    'minimum_accuracy_percentage' => 80,
                    'maximum_accuracy_percentage' => 89.9999,
                    'accuracy_denominator' => 'all_questions',
                    'subject_scoped' => true,
                ],
            ],
            [
                'code' => 'exam_performance.platinum',
                'name' => 'Platinum Subject Performance',
                'description' => 'Scored at least 90% in a completed subject exam practice.',
                'category' => 'exam_performance',
                'type' => 'medal',
                'tier' => 'platinum',
                'scope' => 'attempt',
                'repeatable' => true,
                'progressive' => false,
                'display_order' => 4,
                'requirements' => [
                    'attempt_status' => 'completed',
                    'minimum_accuracy_percentage' => 90,
                    'maximum_accuracy_percentage' => 99.9999,
                    'accuracy_denominator' => 'all_questions',
                    'subject_scoped' => true,
                ],
            ],
            [
                'code' => 'exam_performance.diamond',
                'name' => 'Diamond Subject Performance',
                'description' => 'Scored 100% in a completed subject exam practice.',
                'category' => 'exam_performance',
                'type' => 'medal',
                'tier' => 'diamond',
                'scope' => 'attempt',
                'repeatable' => true,
                'progressive' => false,
                'display_order' => 5,
                'requirements' => [
                    'attempt_status' => 'completed',
                    'minimum_accuracy_percentage' => 100,
                    'maximum_accuracy_percentage' => 100,
                    'accuracy_denominator' => 'all_questions',
                    'subject_scoped' => true,
                ],
            ],
            [
                'code' => 'time_investment.one_hour_learner',
                'name' => '1 Hour Learner',
                'description' => 'Spent one cumulative hour in exam practice.',
                'category' => 'time_investment',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 1,
                'requirements' => [
                    'active_seconds' => 3600,
                    'scope' => 'all_subjects',
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'time_investment.ten_hours_scholar',
                'name' => '10 Hours Scholar',
                'description' => 'Spent ten cumulative hours in exam practice.',
                'category' => 'time_investment',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 2,
                'requirements' => [
                    'active_seconds' => 36000,
                    'scope' => 'all_subjects',
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'time_investment.twenty_five_hours_learner',
                'name' => '25 Hours Learner',
                'description' => 'Spent 25 cumulative hours in exam practice.',
                'category' => 'time_investment',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 3,
                'requirements' => [
                    'active_seconds' => 90000,
                    'scope' => 'all_subjects',
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'time_investment.fifty_hours_scholar',
                'name' => '50 Hours Scholar',
                'description' => 'Spent 50 cumulative hours in exam practice.',
                'category' => 'time_investment',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 4,
                'requirements' => [
                    'active_seconds' => 180000,
                    'scope' => 'all_subjects',
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'time_investment.one_hundred_hour_academic_hero',
                'name' => '100 Hour Academic Hero',
                'description' => 'Spent 100 cumulative hours in exam practice.',
                'category' => 'time_investment',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 5,
                'requirements' => [
                    'active_seconds' => 360000,
                    'scope' => 'all_subjects',
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'time_investment.two_hundred_fifty_hours_study_master',
                'name' => '250 Hours Study Master',
                'description' => 'Spent 250 cumulative hours in exam practice.',
                'category' => 'time_investment',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 6,
                'requirements' => [
                    'active_seconds' => 900000,
                    'scope' => 'all_subjects',
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'time_investment.five_hundred_hours_education_legend',
                'name' => '500 Hours Education Legend',
                'description' => 'Spent 500 cumulative hours in exam practice.',
                'category' => 'time_investment',
                'type' => 'badge',
                'scope' => 'lifetime',
                'progressive' => true,
                'display_order' => 7,
                'requirements' => [
                    'active_seconds' => 1800000,
                    'scope' => 'all_subjects',
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'speed.quick_thinker',
                'name' => 'Quick Thinker',
                'description' => 'Answered a question correctly within 60 seconds.',
                'category' => 'speed',
                'type' => 'medal',
                'scope' => 'attempt_question',
                'repeatable' => true,
                'requirements' => [
                    'correct' => true,
                    'maximum_response_duration_ms' => 60000,
                    'consecutive' => true,
                ],
            ],
            [
                'code' => 'speed.fast_learner',
                'name' => 'Fast Learner',
                'description' => 'Answered three consecutive questions correctly within 3 minutes 20 seconds.',
                'category' => 'speed',
                'type' => 'medal',
                'scope' => 'attempt_window',
                'repeatable' => true,
                'requirements' => [
                    'correct' => true,
                    'question_count' => 3,
                    'maximum_total_duration_ms' => 200000,
                    'consecutive' => true,
                ],
            ],
            [
                'code' => 'speed.lightning_brain',
                'name' => 'Lightning Brain',
                'description' => 'Answered seven consecutive questions correctly within 8 minutes.',
                'category' => 'speed',
                'type' => 'medal',
                'scope' => 'attempt_window',
                'repeatable' => true,
                'requirements' => [
                    'correct' => true,
                    'question_count' => 7,
                    'maximum_total_duration_ms' => 480000,
                    'consecutive' => true,
                ],
            ],
            [
                'code' => 'speed.speed_champion',
                'name' => 'Speed Champion',
                'description' => 'Answered ten consecutive questions correctly within 11 minutes 30 seconds.',
                'category' => 'speed',
                'type' => 'medal',
                'scope' => 'attempt_window',
                'repeatable' => true,
                'requirements' => [
                    'correct' => true,
                    'question_count' => 10,
                    'maximum_total_duration_ms' => 690000,
                    'consecutive' => true,
                ],
            ],
            [
                'code' => 'speed.speed_legend',
                'name' => 'Speed Legend',
                'description' => 'Answered fifteen consecutive questions correctly within 16 minutes.',
                'category' => 'speed',
                'type' => 'medal',
                'scope' => 'attempt_window',
                'repeatable' => true,
                'requirements' => [
                    'correct' => true,
                    'question_count' => 15,
                    'maximum_total_duration_ms' => 960000,
                    'consecutive' => true,
                ],
            ],
            [
                'code' => 'improvement.rising_star',
                'name' => 'Rising Star',
                'description' => 'Improved from below 40% to at least 50% weekly accuracy.',
                'category' => 'improvement',
                'type' => 'badge',
                'scope' => 'weekly_transition',
                'repeatable' => true,
                'requirements' => [
                    'previous_maximum_accuracy_percentage' => 40,
                    'current_minimum_accuracy_percentage' => 50,
                    'minimum_improvement_percentage_points' => 10,
                ],
            ],
            [
                'code' => 'improvement.comeback_student',
                'name' => 'Comeback Student',
                'description' => 'Recovered by at least 10 percentage points after a weekly decline.',
                'category' => 'improvement',
                'type' => 'badge',
                'scope' => 'weekly_transition',
                'repeatable' => true,
                'requirements' => [
                    'previous_decline_percentage_points' => 10,
                    'recovery_percentage_points' => 10,
                ],
            ],
            [
                'code' => 'improvement.growth_champion',
                'name' => 'Growth Champion',
                'description' => 'Progressed through four or more weekly accuracy bands from below 50%.',
                'category' => 'improvement',
                'type' => 'badge',
                'scope' => 'progression',
                'repeatable' => false,
                'requirements' => [
                    'starting_below_percentage' => 50,
                    'minimum_accuracy_bands_reached' => 4,
                    'bands' => [50, 60, 70, 80],
                ],
            ],
            [
                'code' => 'improvement.determination_medal',
                'name' => 'Determination Medal',
                'description' => 'Maintained below-60% weekly accuracy while spending at least 20 hours in exam practice.',
                'category' => 'improvement',
                'type' => 'medal',
                'scope' => 'weekly',
                'repeatable' => true,
                'requirements' => [
                    'maximum_accuracy_percentage' => 59.9999,
                    'minimum_active_seconds' => 72000,
                ],
            ],
            [
                'code' => 'improvement.excellence_in_progress',
                'name' => 'Excellence in Progress',
                'description' => 'Improved from below 70% to at least 80% weekly accuracy.',
                'category' => 'improvement',
                'type' => 'badge',
                'scope' => 'weekly_transition',
                'repeatable' => true,
                'requirements' => [
                    'previous_maximum_accuracy_percentage' => 69.9999,
                    'current_minimum_accuracy_percentage' => 80,
                ],
            ],
            [
                'code' => 'rank.beginner',
                'name' => 'Beginner',
                'description' => 'Maintained a paid subscription for at least 2 weeks.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 1,
                'requirements' => [
                    'minimum_subscription_weeks' => 2,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'rank.learner',
                'name' => 'Learner',
                'description' => 'Maintained a paid subscription for at least 1 month.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 2,
                'requirements' => [
                    'minimum_subscription_months' => 1,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'rank.explorer',
                'name' => 'Explorer',
                'description' => 'Maintained a paid subscription for at least 2 months.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 3,
                'requirements' => [
                    'minimum_subscription_months' => 2,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'rank.student',
                'name' => 'Student',
                'description' => 'Maintained a paid subscription for at least 3 months.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 4,
                'requirements' => [
                    'minimum_subscription_months' => 3,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'rank.skilled_student',
                'name' => 'Skilled Student',
                'description' => 'Maintained a paid subscription for at least 4 months.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 5,
                'requirements' => [
                    'minimum_subscription_months' => 4,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'rank.scholar',
                'name' => 'Scholar',
                'description' => 'Maintained a paid subscription for at least 5 months.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 6,
                'requirements' => [
                    'minimum_subscription_months' => 5,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'rank.academic_elite',
                'name' => 'Academic Elite',
                'description' => 'Maintained a paid subscription for at least 6 months.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 7,
                'requirements' => [
                    'minimum_subscription_months' => 6,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'rank.excellence_master',
                'name' => 'Excellence Master',
                'description' => 'Maintained a paid subscription for at least 7 months.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 8,
                'requirements' => [
                    'minimum_subscription_months' => 7,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'rank.academic_champion',
                'name' => 'Academic Champion',
                'description' => 'Maintained a paid subscription for at least 8 months.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 9,
                'requirements' => [
                    'minimum_subscription_months' => 8,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'rank.grand_scholar',
                'name' => 'Grand Scholar',
                'description' => 'Maintained a paid subscription for at least 9 months.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 10,
                'requirements' => [
                    'minimum_subscription_months' => 9,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'rank.elite_genius',
                'name' => 'Elite Genius',
                'description' => 'Maintained a paid subscription for at least 10 months.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 11,
                'requirements' => [
                    'minimum_subscription_months' => 10,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'rank.hall_of_fame',
                'name' => 'Hall of Fame',
                'description' => 'Maintained a paid subscription for at least 11 months.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 12,
                'requirements' => [
                    'minimum_subscription_months' => 11,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'rank.education_legend',
                'name' => 'Education Legend',
                'description' => 'Maintained a paid subscription for at least 12 months.',
                'category' => 'rank',
                'type' => 'medal',
                'scope' => 'subscription_duration',
                'progressive' => true,
                'display_order' => 13,
                'requirements' => [
                    'minimum_subscription_months' => 12,
                    'subscription_must_be_paid' => true,
                ],
            ],
            [
                'code' => 'special_event.independence_day_challenge',
                'name' => 'Independence Day Challenge',
                'description' => 'Started an exam practice during the student\'s country independence-day event window.',
                'category' => 'special_event',
                'type' => 'badge',
                'scope' => 'event',
                'repeatable' => true,
                'requirements' => [
                    'event_calendar' => 'country_configured',
                    'minimum_exam_practices_started' => 1,
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'special_event.christmas_learning_champion',
                'name' => 'Christmas Learning Champion',
                'description' => 'Started at least one exam practice on Christmas Day.',
                'category' => 'special_event',
                'type' => 'badge',
                'scope' => 'event',
                'repeatable' => true,
                'requirements' => [
                    'event' => 'christmas_day',
                    'minimum_exam_practices_started' => 1,
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'special_event.new_year_scholar',
                'name' => 'New Year Scholar',
                'description' => 'Started at least one exam practice on New Year\'s Day.',
                'category' => 'special_event',
                'type' => 'badge',
                'scope' => 'event',
                'repeatable' => true,
                'requirements' => [
                    'event' => 'new_year_day',
                    'minimum_exam_practices_started' => 1,
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'special_event.easter_excellence',
                'name' => 'Easter Excellence',
                'description' => 'Started at least one exam practice during the configured Easter event window.',
                'category' => 'special_event',
                'type' => 'badge',
                'scope' => 'event',
                'repeatable' => true,
                'requirements' => [
                    'event' => 'easter',
                    'minimum_exam_practices_started' => 1,
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'special_event.summer_learning_hero',
                'name' => 'Summer Learning Hero',
                'description' => 'Started at least four exam practices during the first two days of the configured summer period.',
                'category' => 'special_event',
                'type' => 'badge',
                'scope' => 'event',
                'repeatable' => true,
                'requirements' => [
                    'event' => 'summer_start',
                    'window_days' => 2,
                    'minimum_exam_practices_started' => 4,
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'special_event.back_to_school_champion',
                'name' => 'Back to School Champion',
                'description' => 'Started at least three exam practices during the configured back-to-school event window.',
                'category' => 'special_event',
                'type' => 'badge',
                'scope' => 'event',
                'repeatable' => true,
                'requirements' => [
                    'event' => 'back_to_school',
                    'minimum_exam_practices_started' => 3,
                    'tracked_activity' => 'exam_practice',
                ],
            ],
            [
                'code' => 'leaderboard.top_one_hundred',
                'name' => 'Top 100',
                'description' => 'Placed within the top 100 students on the global leaderboard.',
                'category' => 'leaderboard',
                'type' => 'medal',
                'scope' => 'leaderboard_period',
                'repeatable' => true,
                'requirements' => ['maximum_rank' => 100],
            ],
            [
                'code' => 'leaderboard.top_fifty',
                'name' => 'Top 50',
                'description' => 'Placed within the top 50 students on the global leaderboard.',
                'category' => 'leaderboard',
                'type' => 'medal',
                'scope' => 'leaderboard_period',
                'repeatable' => true,
                'requirements' => ['maximum_rank' => 50],
            ],
            [
                'code' => 'leaderboard.top_twenty_five',
                'name' => 'Top 25',
                'description' => 'Placed within the top 25 students on the global leaderboard.',
                'category' => 'leaderboard',
                'type' => 'medal',
                'scope' => 'leaderboard_period',
                'repeatable' => true,
                'requirements' => ['maximum_rank' => 25],
            ],
            [
                'code' => 'leaderboard.top_ten',
                'name' => 'Top 10',
                'description' => 'Placed within the top 10 students on the global leaderboard.',
                'category' => 'leaderboard',
                'type' => 'medal',
                'scope' => 'leaderboard_period',
                'repeatable' => true,
                'requirements' => ['maximum_rank' => 10],
            ],
            [
                'code' => 'leaderboard.top_five',
                'name' => 'Top 5',
                'description' => 'Placed within the top 5 students on the global leaderboard.',
                'category' => 'leaderboard',
                'type' => 'medal',
                'scope' => 'leaderboard_period',
                'repeatable' => true,
                'requirements' => ['maximum_rank' => 5],
            ],
            [
                'code' => 'leaderboard.top_three',
                'name' => 'Top 3',
                'description' => 'Placed within the top 3 students on the global leaderboard.',
                'category' => 'leaderboard',
                'type' => 'medal',
                'scope' => 'leaderboard_period',
                'repeatable' => true,
                'requirements' => ['maximum_rank' => 3],
            ],
            [
                'code' => 'leaderboard.number_one_student',
                'name' => '#1 Student',
                'description' => 'Placed first on the global leaderboard.',
                'category' => 'leaderboard',
                'type' => 'medal',
                'scope' => 'leaderboard_period',
                'repeatable' => true,
                'requirements' => ['maximum_rank' => 1],
            ],
            [
                'code' => 'leaderboard.weekly_champion',
                'name' => 'Weekly Champion',
                'description' => 'Achieved the highest global weekly leaderboard ranking.',
                'category' => 'leaderboard',
                'type' => 'badge',
                'scope' => 'weekly',
                'repeatable' => true,
                'requirements' => ['period' => 'weekly', 'rank' => 1],
            ],
            [
                'code' => 'leaderboard.monthly_champion',
                'name' => 'Monthly Champion',
                'description' => 'Achieved the highest global monthly leaderboard ranking.',
                'category' => 'leaderboard',
                'type' => 'badge',
                'scope' => 'monthly',
                'repeatable' => true,
                'requirements' => ['period' => 'monthly', 'rank' => 1],
            ],
            [
                'code' => 'leaderboard.all_time_champion',
                'name' => 'All-Time Champion',
                'description' => 'Achieved the highest global all-time leaderboard ranking.',
                'category' => 'leaderboard',
                'type' => 'badge',
                'scope' => 'all_time',
                'repeatable' => true,
                'requirements' => ['period' => 'all_time', 'rank' => 1],
            ],
            [
                'code' => 'exam_preparation.jamb_ready',
                'name' => 'JAMB Ready',
                'description' => 'Completed a successful subscription for JAMB preparation.',
                'category' => 'exam_preparation',
                'type' => 'badge',
                'scope' => 'once',
                'progressive' => true,
                'requirements' => [
                    'exam_body' => 'jamb',
                    'payment_status' => 'successful',
                ],
            ],
            [
                'code' => 'exam_preparation.waec_ready',
                'name' => 'WAEC Ready',
                'description' => 'Completed a successful subscription for WAEC preparation.',
                'category' => 'exam_preparation',
                'type' => 'badge',
                'scope' => 'once',
                'progressive' => true,
                'requirements' => [
                    'exam_body' => 'waec',
                    'payment_status' => 'successful',
                ],
            ],
            [
                'code' => 'exam_preparation.neco_ready',
                'name' => 'NECO Ready',
                'description' => 'Completed a successful subscription for NECO preparation.',
                'category' => 'exam_preparation',
                'type' => 'badge',
                'scope' => 'once',
                'progressive' => true,
                'requirements' => [
                    'exam_body' => 'neco',
                    'payment_status' => 'successful',
                ],
            ],
            [
                'code' => 'exam_preparation.gce_ready',
                'name' => 'GCE Ready',
                'description' => 'Completed a successful subscription for GCE preparation.',
                'category' => 'exam_preparation',
                'type' => 'badge',
                'scope' => 'once',
                'progressive' => true,
                'requirements' => [
                    'exam_body' => 'gce',
                    'payment_status' => 'successful',
                ],
            ],
        ];

        foreach ($achievements as $definition) {
            Achievement::updateOrCreate(
                ['code' => $definition['code']],
                array_merge(
                    [
                        'tier' => null,
                        'repeatable' => false,
                        'icon_path' => null,
                        'is_active' => true,
                        'starts_at' => null,
                        'ends_at' => null,
                    ],
                    $definition
                )
            );
        }
    }
}
