<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('exam_question_interactions', function (Blueprint $table) {
            $table->id();

            $table->foreignId('exam_attempt_id')
                ->constrained('exam_attempts')
                ->cascadeOnDelete();

            $table->foreignId('student_id')
                ->constrained('students')
                ->cascadeOnDelete();

            $table->foreignId('past_question_id')
                ->constrained('past_questions')
                ->cascadeOnDelete();

            $table->foreignId('past_question_option_id')
                ->nullable()
                ->constrained('past_question_options')
                ->nullOnDelete();

            $table->unsignedInteger('sequence_number');

            // viewed, answered, skipped, or timed_out
            $table->string('action');

            // Snapshot correctness so historical awards do not change if options are edited.
            $table->boolean('is_correct')->nullable();

            $table->timestamp('question_shown_at')->nullable();
            $table->timestamp('action_submitted_at')->nullable();
            $table->unsignedBigInteger('response_duration_ms')->nullable();

            // Generated by the frontend for safe retries and duplicate prevention.
            $table->uuid('client_event_id')->unique();

            $table->json('metadata')->nullable();

            $table->timestamps();

            $table->index(
                ['exam_attempt_id', 'sequence_number'],
                'exam_interaction_attempt_sequence_index'
            );

            $table->index(['student_id', 'action_submitted_at']);
            $table->index(['exam_attempt_id', 'action']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('exam_question_interactions');
    }
};
